### ISSUE TITLE
KSCrash

### ISSUE THREAD

**Issue by mackoj** [bitstadium/CrashProbe#2]
Thanks for giving us a way to test crash reporters.

It's would be interesting to see how [KSCrash](https://github.com/kstenerud/KSCrash) performs.

Is the CrashProbe site updated with the last version of HockeyApp which use PLCrashReporter 1.2 ?

**Comment by anlinde** [comment]
It is now possible to contribute data from additional services yourself, see https://github.com/bitstadium/CrashProbe-Data/
