### ISSUE TITLE
Data for Crashlytics is now years out-of-date

### ISSUE THREAD

**Issue by AWrightIV** [bitstadium/CrashProbe#5]
The data [hosted on the CrashProbe site](http://www.crashprobe.com/ios/) is now wildly out-of-date with the latest versions of these analytics packages. For example, the Crashlytics tested at the time of the last run was [version 3.4.1 from November 19, 2015](https://docs.fabric.io/apple/changelog.html#november-19-2015) where the latest is 3.8.4 from February 22, 2017. Please update the results.

**Comment by anlinde** [comment]
Yes, we plan to update the data in the coming weeks. As it is a lot of effort (multi days) to collect the data and evaluate it and for some we don't get the data provided, it sometimes takes a while.

We do have a public process were any provider can send us the data, and some do it, see https://github.com/bitstadium/CrashProbe-Data

We'd love to have everything always up to do, but sadly this doesn't scale that easily.

**Comment by anlinde** [comment]
Hi,

we decided to remove the Crashlytics data overall. We won't test other 3rd party services from our end but rely on them providing their test results just like all now showing datasets are provided.

We'll update the Apple dataset (what Xcode shows, not what iTunes Connect shows) in the coming weeks.
